### ISSUE TITLE
[Feature] Add regional context objects to a scene

### ISSUE THREAD

**Issue by PlasticMohawk** [cswendrowski/FoundryVTT-Intelligent-NPCs#16]
Use case:
As a Foundry GM, I set up Foundry scenes using multiple background images as tiles, bounded by walls. Thus, a single scene can consist of an entire multi-use building, for example, with many different rooms. In addition to walls, each image is bounded by a Drawing object, so the Lock View module will keep the entire room a player token is in within view for that player.

![image](https://github.com/cswendrowski/FoundryVTT-Intelligent-NPCs/assets/5216225/aadad9b9-a922-4b7f-81a7-bbade453b71f)

I want to contextualize my "scene info" on a per-room basis, so that I may have different situations going on in different rooms. The result is that the iNPC could comment about different parts of the scene local to the actor token.

Take for example a fantasy magic shop. On one side of the room are the potions for sale. On the other side, the scrolls for sale.
The scene itself would have general information about the magic shop.
A region within the scene would have information about the potion selection. ("This magic shop has such a great potion selection!")
Another region within the scene would have information about the scrolls selection. ("This magic shop has such a great scroll selection!")
If the regions overlap, the context sent to the iNPC would be additive. ("This magic shop has such a great selection of potions and scrolls!")

This could be handled via Drawings or v12 Scene Regions, etc.

![image](https://github.com/cswendrowski/FoundryVTT-Intelligent-NPCs/assets/5216225/c3ffae26-2b87-4af7-8b18-a635f99f3a78)

Here is some code which may help determine whether a token is within one or more polygon drawings.

```
const TAGS = ["LVL01", "LVL02", "LVL03", "LVL04", "LVL05", "goblins", "kobolds", "wyverns"];
let encTables = [];
// Get all drawings by tag
// add them to an array of drawing objects
let objects = [];
for (let tag of TAGS) {
    let result = await Tagger.getByTag(tag, worldMapObject);
    objects = objects.concat(result);
}
for (let drawing of objects) {
    if (drawing.shape.type === "p") {
        // Get the points of the polygon
        let points = drawing.shape.points;
        let polygon = new PIXI.Polygon(points);
        const { x, y } = token.center;

        if (polygon.contains((x - drawing.x), (y - drawing.y))) {
            for (let tag of TAGS) {
                if (Tagger.hasTags(drawing, tag)) {
                    let tableName = capitalizeFirstLetter(tag);
                    encTables.push(game.tables.getName(tableName));
                }
            }
        }
    }
}
```

**Comment by cswendrowski** [comment]
This feature is now done, and will be released later this week!
